# Learning Python Functions

In [3]:
def count(i):
    for a in range(i):
        print(a)

count(2)

0
1


# Investigating Numpy and Pandas

## Installing Numpy

In [ ]:
pip install numpy

##  Creating Arrays

In [4]:
import numpy as np

a = [1,2,3]

x = np.array(a)
print(x)

y = np.array([[[[1,2],[2,3]],[[1,2],[2,3]]],[[[1,2],[2,3]],[[1,2],[2,3]]]])
print(y)


[1 2 3]
[[[[1 2]
   [2 3]]

  [[1 2]
   [2 3]]]


 [[[1 2]
   [2 3]]

  [[1 2]
   [2 3]]]]


## Installing Pandas

In [ ]:
pip install pandas

## Creating Series and Dataframes

In [5]:
import pandas as pd

s = pd.Series([10,20,30,40],name='MyNumbers')
print(f"Pandas series:\{s}")
print(f"Type of Series:{type(s)}")

dataframe = {
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,39,40,12],
    'City': ['New York','London','Paris','New York'],
    'Salary': [70000,80000,90000,0]
}

df = pd.DataFrame(dataframe)
print(df)

Pandas series:\0    10
1    20
2    30
3    40
Name: MyNumbers, dtype: int64
Type of Series:<class 'pandas.core.series.Series'>
      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   39    London   80000
2  Charlie   40     Paris   90000
3    David   12  New York       0


In [6]:
df

Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   39    London   80000
2  Charlie   40     Paris   90000
3    David   12  New York       0